import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/Navbar"
import Header from "../components/Header/Header"
import Footer from "../components/Footer/Footer"
import CustomCursor from '../components/Cursor/CustomCursor';
// import NextCustomCursor from '../components/Cursor2/NextCustomCursor';
import Link from 'next/link'
import style from '../typography/typography.module.css'
import {sectionText} from "../typography/fonts"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"body"}>
      < CustomCursor />
      {/* < NextCustomCursor /> */}
        <div className="navBar">
          <Navbar/>
        </div>
        <div className="page">
          <div className="header">
            <Header/>
          </div>
          <div className="content">
            {children}
          </div>
          <div className="footer">
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
